### ISSUE TITLE
What about CDPATH?

### ISSUE THREAD

**Issue by mark-i-m** [arthurp/jumpto#1]
I'm curious how this differs from `CDPATH`

**Comment by arthurp** [comment]
This is mainly the result of me procrastinating and writing random code (read: I didn't look for other implementations of this). However, there is one thing this can do CDPATH cannot do: _Go to directories based on suffixes of the directory instead of just a subdirectories._ For example, `jp blarg` could be take you to /home/me/project-blarg.

**Comment by mark-i-m** [comment]
Ok, good to know :)
